### ISSUE TITLE
Postgres 13.4 Failed to start

### ISSUE THREAD

**Issue by jharrilim** [CircleCI-Public/cimg-postgres#21] opened 2021-11-16 03:49 UTC
# Summary

Currently Postgres fails to start when running:

```sh
docker run --rm -it cimg/postgres:13.4
```

or from CircleCI:

```sh
executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/postgres:13.4
```

---

Last bit of the logs:

```txt
Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-11-16 03:38:50.202 UTC [53] LOG:  starting PostgreSQL 13.4 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-11-16 03:38:50.204 UTC [53] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-11-16 03:38:50.210 UTC [54] LOG:  database system was shut down at 2021-11-16 03:38:49 UTC
2021-11-16 03:38:50.217 UTC [53] LOG:  database system is ready to accept connections
 done
server started
psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**Comment by sue445** [comment] 2021-11-19 00:40
I saw the same error on `cimg/postgres:9.6` too.

* https://app.circleci.com/pipelines/github/sue445/ccc_privacy_crawler/1294/workflows/706b5e3e-a7a4-4de6-a0c1-39a05a7ff350/jobs/4439
* https://app.circleci.com/pipelines/github/sue445/sebastian-badge/1458/workflows/90e3e3bd-654a-4591-8ed0-ee3d58be70b3/jobs/4947

**Comment by BytesGuy** [comment] 2021-12-08 11:57
Hi, can you re-test these images? We have made some changes that should resolve this issue, at least in the 9.6 image (I was unable to reproduce the issue in 13.4 even before these changes). Thanks!

**Comment by BytesGuy** [comment] 2021-12-16 11:57
I'm going to close this issue as I can no longer reproduce the issue on any images. If this continues to be a problem, please feel free to re-open the issue. Thanks!

**Closed by BytesGuy** 2021-12-16 11:57 UTC
